#---------------------------------------------------------------------------
# Configuration file for performance test suite
#---------------------------------------------------------------------------

default {
    # viz data source (web, csv).
    # When data source is web, the program will connect to tableau server and fetch all the available views from all the sites. Note that you will need to provide administrator user name and password in ServerTestConfig.yaml file.
    # When data source is csv, each row needs to be define in this format "/views/%workbook%/%viz%" for default site or "/site/%site%/views/%workbook%/%viz%"
    vizDataSource: csv
    csvFileName: vizpool.csv
    # use forceLogin parameter to control whether to force login. By default, tabjolt will detect whether guest mode is turned on. If yes, it will not try to logon.
    # If no, it will try to logon at the beginning of the test case.
    # the parameter is to override the behavior. If it is set to true, then it will always try to logon. If it is set to false, then it will fall back to the previous behavior
    forceLogin: false
    # Tabjolt now support login from a pool of users which are specified in the userpool.csv file. It will randomly pick users from the user pool folder
    # the format of the userpool.csv is UserName,Password,Role. Role is the user server role which could be either ServerAdmin or ViewerOrInteractor. Here is an example:
    # john,password,ServerAdmin
    # kevin,password,ViewerOrInteractor
    loginUsersCsvFileName: userpool.csv
    # set think time to create a pause between tests
    thinktimeBetweenTest: 0
    # set think time to create a pause between view and interaction operation for an interact test test
    thinktimeBeforeInteraction: 0
    insertOnlyParentSamples: false
    reusePresModels: false
    # the run will be terminated if the maximum errors have been reached during the run.
    invalidateRunAfterMaxErrors: true
    maximumErrorsInvalidRun: 100000

    # The settings below are moved from PerfRunHarness.properties
    DBType: postgres
    DBUserName: postgres
    DBPassword: testresults
    DBServerName: localhost
    DBPort: 5432
    DBName: PerfResults
}