#---------------------------------------------------------------------------
# Configuration file for performance test suite
#---------------------------------------------------------------------------

default {
    # viz data source (web, csv).
    # When data source is web, the program will connect to tableau server and fetch all the available views from all the sites. Note that you will need to provide administrator user name and password in ServerTestConfig.yaml file.
    # When data source is csv, each row needs to be define in this format "/views/%workbook%/%viz%" for default site or "/site/%site%/views/%workbook%/%viz%"
    vizDataSource: csv
    csvFileName: vizpool.csv
    reusePresModels: true
}