#---------------------------------------------------------------------------
# Configuration file for performance test suite
#---------------------------------------------------------------------------

default {
    # viz data source (db, csv).
    # When data source is db, the program will connect to tableau postgres database and fetch the available views.
    # When data source is csv, each row needs to be define in this format "/views/%workbook%/%viz%"
    vizDataSource: csv
    csvFileName: vizpool.csv
}