#---------------------------------------------------------------------------
# Configuration file for server test suite
#---------------------------------------------------------------------------

default {
    # tableau server host name:
    hostUri: http://localhost

    # HTTP User-Agent
    userAgent: java-client-requests

    users:
        - !!com.tableausoftware.test.server.configuration.User          
          name:
          password:
}
