#---------------------------------------------------------------------------
# Configuration file for server test suite
#---------------------------------------------------------------------------

default {
    # tableau server host name:
    hostUri: http://localhost

    # HTTP User-Agent
    userAgent: java-client-requests

    # server database connection information
    database:
        connectionString: jdbc:postgresql://%s:%s
        serverName: 10.17.136.103
        port: 8060
        databaseName: workgroup
        userName: readonly
        password: readonly
        driver: org.postgresql.Driver
        unicode: true
        encoding: utf-8

    users:
        - !!com.tableausoftware.test.server.configuration.User          
          name:  
          password: 
}
